#!/bin/bash

set -e

STABLE=8.8
DEV=8.9

if [ $DOCKER_TAG == "stable" ]; then
    HTCONDOR_VERSION=STABLE
elif [ $DOCKER_TAG == "dev" ]; then
    HTCONDOR_VERSION=DEV
else
    HTCONDOR_VERSION=$DOCKER_TAG
fi

docker build --build-arg HTCONDOR_VERSION -f $DOCKERFILE_PATH -t $IMAGE_NAME .
